services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mrcado_app
    volumes:
      - ./backend:/var/www/html
      - ./packages:/var/www/packages
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: mrcado
      DB_USERNAME: mrcado
      DB_PASSWORD: secret
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:15
    container_name: mrcado_db
    environment:
      POSTGRES_USER: mrcado
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mrcado
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: mrcado_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mrcado_rabbit
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  pgdata: